In [1]:
import torch
import numpy as np 
import time 
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 18,  24, -49,  14, -43,  96])

In [3]:
tensor = torch.tensor([[0.1,0.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 0.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[5039259129968,             0,             0],
        [            0,             0,             0]])

In [12]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000


# Record time taken for cell to execute using time library %%time

In [13]:
%%time
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()


elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


# Iterative processing

In [14]:
"""
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)
np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")
"""

# Test with GPU (cuda)



'\ntorch_rand1 = torch.rand(10000, 10000).to(device)\ntorch_rand2 = torch.rand(10000, 10000).to(device)\nnp_rand1 = torch.rand(10000, 10000)\nnp_rand2 = torch.rand(10000, 10000)\n\nstart_time = time.time()\n\nrand = (torch_rand1 @ torch_rand2)\n\nend_time = time.time()\n\nrand = np.multiply(np_rand1, np_rand2)\nend_time = time.time()\nelapsed_time = end_time - start_time\nprint(f"{elapsed_time:.8f}")\n'

In [15]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F. softmax (all examples of functions/method with pytorch docs)


#Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1 => 0, 90% or 0.9 => 1 . each probability points to the index of the probability in the tensor 
#Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)




tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float("-inf"))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape



torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])


In [23]:
tensor1 = torch.tensor([1, 2, 3,])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias= False)
print(linear(sample))

tensor([-4.5543,  2.9705, -4.8430], grad_fn=<SqueezeBackward4>)


In [25]:
import torch.nn.functional as F

#Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Apply softmax using torch.nn.functional.softmax()

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)


tensor([0.0900, 0.2447, 0.6652])


In [26]:
#Initialize an embedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

#create input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#applying embedding layer
embedded_output = embedding(input_indices)

#The output will be a tesnor of a shape (4,100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [27]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
#print(a @ b)
print(torch.matmul(a,b))


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [28]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64

float_32 = torch.rand(2,3)
#type float32 
#print(int_64.dtype, float_32.dtype)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [31]:
a = torch.rand(2, 3 ,5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])
